spring:
  profiles:
    active: dev

server:
  port: 8080

---
spring:
  config:
    activate:
      on-profile: dev
  driver-class-name: org.postgresql.Driver
  username: egsp
  password: egsp1234!@
  int-url: jdbc:postgresql://172.30.1.40:5432/egis21_egsp
  ext-url: jdbc:postgresql://172.30.1.60:5432/egis21_egsp
  datasource-int:
    driver-class-name: ${spring.driver-class-name}
    jdbc-url: ${spring.int-url}
    url: ${spring.int-url}
    username: ${spring.username}
    password: ${spring.password}
  datasource-ext:
    driver-class-name: ${spring.driver-class-name}
    jdbc-url: ${spring.ext-url}
    url: ${spring.ext-url}
    username: ${spring.username}
    password: ${spring.password}

gisen:
  task:
    thread-count: 10
    run-check: 60000
    stop-check: 60000

sync:
  work-path: '\\172.30.1.4\nas_2tb\egsp_int_nas\rsync_copyout_dir'

logging:
  paths:
    log_dir: 'X:\egsp_int_nas\log_rsync'
  pattern:
    file: '[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n'
  file:
    name: '${logging.paths.log_dir}\egsp_rsync.log'
  logback:
    rolling_policy:
      file_name_pattern: '${logging.paths.log_dir}\egsp_rsync.%d{yyyy-MM-dd}.%i'
  level:
    root: info
    sql: error
    jdbc: off
    jdbc.sqlonly: debug
    kr.go.me.egis.egsp.rsync: debug

---
spring:
  config:
    activate:
      on-profile: prod
  driver-class-name: org.postgresql.Driver
  username: egsp
  password: egsp1234!@#
  int-url: jdbc:postgresql://10.177.195.88:9999/egis21_egsp
  ext-url: jdbc:postgresql://10.176.202.107:9999/egis21_egsp
  datasource-int:
    driver-class-name: ${spring.driver-class-name}
    jdbc-url: ${spring.int-url}
    url: ${spring.int-url}
    username: ${spring.username}
    password: ${spring.password}
  datasource-ext:
    driver-class-name: ${spring.driver-class-name}
    jdbc-url: ${spring.ext-url}
    url: ${spring.ext-url}
    username: ${spring.username}
    password: ${spring.password}

gisen:
  task:
    thread-count: 10
    run-check: 60000
    stop-check: 60000

sync:
  work-path: '/ESDATA/egsp_rsync'

logging:
  paths:
    log_dir: '/ESDATA/egsp_rsync/log'
  pattern:
    file: '[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n'
  file:
    name: '${logging.paths.log_dir}/egsp_rsync.log'
  logback:
    rolling_policy:
      file_name_pattern: '${logging.paths.log_dir}/egsp_rsync.%d{yyyy-MM-dd}.%i'
  level:
    root: info
    sql: error
    jdbc: off
    jdbc.sqlonly: off
    kr.go.me.egis.egsp.rsync: debug

