spring:
  profiles:
    active: dev

server:
  port: 8090

---
spring:
  config:
    activate:
      on-profile: dev
  driver-class-name: org.postgresql.Driver
  username: egsp
  password: egsp1234!@
  datasource-int:
    driver-class-name: ${spring.driver-class-name}
    jdbc-url: jdbc:postgresql://172.30.1.40:5432/egis21_egsp
    url: jdbc:postgresql://172.30.1.40:5432/egis21_egsp
    username: ${spring.username}
    password: ${spring.password}
  datasource-ext:
    driver-class-name: ${spring.driver-class-name}
    jdbc-url: jdbc:postgresql://172.30.1.60:5432/egis21_egsp
    url: jdbc:postgresql://172.30.1.60:5432/egis21_egsp
    username: ${spring.username}
    password: ${spring.password}

gisen:
  task:
    thread-count: 10
    run-check: 10000
    stop-check: 60000

sync:
  work-path: '\\172.30.1.4\nas_2tb\egsp_int_nas\rsync_copyout_dir'

logging:
  level:
    root: info
    sql: error
    jdbc: off
    jdbc.sqlonly: debug
    kr.go.me.egis.egsp.rsync: debug


---
spring:
  config:
    activate:
      on-profile: prod
  datasource-int:
    jdbc-url: jdbc:postgresql://10.175.85.148:5432/egis21_egsp
    username: egsp
    password: egsp1234!@

  datasource-ext:
    jdbc-url: jdbc:postgresql://172.30.1.60:5432/egis21_egsp
    username: egsp
    password: egsp1234!@


logging:
  level:
    root: info
    sql: error
    jdbc: off
    jdbc.sqlonly: debug
    kr.go.me.egis.egsp.rsync: debug

