spring:
  profiles:
    active: dev

server:
  port: 8090

---
spring:
  profiles: dev
  driver-class-name: org.postgresql.Driver
  username: egsp
  password: egsp1234!@
  datasource-int:
    driver-class-name: ${spring.driver-class-name}
    url: jdbc:postgresql://172.30.1.40:5432/egis21_egsp
    username: ${spring.username}
    password: ${spring.password}
  datasource-ext:
    driver-class-name: ${spring.driver-class-name}
    url: jdbc:postgresql://172.30.1.60:5432/egis21_egsp
    username: ${spring.username}
    password: ${spring.password}

logging:
  level:
    root: info
    sql: error
    jdbc: off
    jdbc.sqlonly: debug
    kr.go.me.egis.egsp.rsync: debug


---
spring:
  profiles: prod
  datasource-int:
    jdbc-url: jdbc:postgresql://10.175.85.148:5432/egis21_egsp
    username: egsp
    password: egsp1234!@

  datasource-ext:
    jdbc-url: jdbc:postgresql://172.30.1.60:5432/egis21_egsp
    username: egsp
    password: egsp1234!@

logging:
  level:
    root: info
    sql: error
    jdbc: off
    jdbc.sqlonly: debug
    kr.go.me.egis.egsp.rsync: debug

